/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todoApp;

import controller.ProjectController;
import controller.TaskController;
import java.sql.Connection;
import java.sql.Date;
import java.time.Instant;
import java.time.LocalDate;
import static java.time.LocalDate.now;
import java.util.List;
import model.Project;
import model.Task;
import util.ConnectionFactory;

public class App {

//    public String getGreeting() {
//        return "Hello World!";
//    }
    public static void main(String[] args) {
//        System.out.println(new App().getGreeting());
//
//        Connection conn = null;
//        conn = ConnectionFactory.getConnection();
//        System.out.println("Conexão estabelecida");

//        ProjectController projectController = new ProjectController();
//
//        Project project = new Project();
//        project.setName("Projeto teste");
//        project.setDescription("Descripton");
//        projectController.save(project);




//        ProjectController projectController = new ProjectController();
//        Project project = new Project();
//        project.setId(6);
//        project.setName("Novo nome do projeto");
//        project.setDescription("New Description");
//        projectController.update(project);
//
//      List<Project> projects = projectController.getAll();
//        System.out.println("Total de Projetos = " + projects.size());
//        
//        projectController.removeById(6);


TaskController cont = new TaskController();
Task task = new Task();

//task.setIdProject(1);
//task.setName("Teste404");
//task.setDescription("Vai dar certo essa merda");
//task.setIsCompleted(true);
//
//cont.save(task);
//task.setId(2);
//task.setIdProject(2);
//task.setName("NEW NAME");
//task.setDescription("Pronto!!");
//
//cont.update(task);

cont.removeById(2);



















    }
}
