/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ProjectController;
import controller.TaskController;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.DefaultListModel;
import model.Project;
import model.Task;
import util.TaskTableModel;

/**
 *
 * @author Wesley
 */
public class MainScreen extends javax.swing.JFrame {

    ProjectController projectController;
    TaskController taskController;

    DefaultListModel projectsModel;
    TaskTableModel taskModel;

    public MainScreen() {
        initComponents();
        decorateTableTask();

        initDataController();
        initComponentsModel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1Tasks = new javax.swing.JTable();
        jpanelToolbar = new javax.swing.JPanel();
        jLabel1ToobarTitle = new javax.swing.JLabel();
        jLabel2ToobarSubtitle = new javax.swing.JLabel();
        jPanel2Projects = new javax.swing.JPanel();
        jLabel3Projects = new javax.swing.JLabel();
        jLabel7ProjectsAdd = new javax.swing.JLabel();
        jPanel3Tasks = new javax.swing.JPanel();
        jLabel4TasksTitle = new javax.swing.JLabel();
        jLabel6TasksAdd = new javax.swing.JLabel();
        jPanel4ProjectList = new javax.swing.JPanel();
        jScrollPane1Projects = new javax.swing.JScrollPane();
        jList1Projects = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        jPanelEmptyList = new javax.swing.JPanel();
        jLabel5EmptyListIcon = new javax.swing.JLabel();
        jLabel8EmptyListTitle = new javax.swing.JLabel();
        jLabel9EmptyListSubtitle = new javax.swing.JLabel();

        jTable1Tasks.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTable1Tasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Descrição", "Prazo", "Tarefa Concluida"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1Tasks.setGridColor(java.awt.Color.white);
        jTable1Tasks.setRowHeight(50);
        jTable1Tasks.setSelectionBackground(new java.awt.Color(153, 255, 153));
        jTable1Tasks.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1Tasks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1TasksMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1Tasks);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 650));

        jpanelToolbar.setBackground(new java.awt.Color(0, 153, 105));

        jLabel1ToobarTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1ToobarTitle.setForeground(java.awt.Color.white);
        jLabel1ToobarTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tick.png"))); // NOI18N
        jLabel1ToobarTitle.setText(" Todo App");

        jLabel2ToobarSubtitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2ToobarSubtitle.setForeground(java.awt.Color.white);
        jLabel2ToobarSubtitle.setText("Anote tudo, não esqueça nada");

        javax.swing.GroupLayout jpanelToolbarLayout = new javax.swing.GroupLayout(jpanelToolbar);
        jpanelToolbar.setLayout(jpanelToolbarLayout);
        jpanelToolbarLayout.setHorizontalGroup(
            jpanelToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelToolbarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanelToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1ToobarTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2ToobarSubtitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jpanelToolbarLayout.setVerticalGroup(
            jpanelToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelToolbarLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1ToobarTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2ToobarSubtitle)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel2Projects.setBackground(java.awt.Color.white);
        jPanel2Projects.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3Projects.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3Projects.setForeground(new java.awt.Color(0, 153, 102));
        jLabel3Projects.setText("Projetos");

        jLabel7ProjectsAdd.setForeground(java.awt.Color.white);
        jLabel7ProjectsAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        jLabel7ProjectsAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7ProjectsAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2ProjectsLayout = new javax.swing.GroupLayout(jPanel2Projects);
        jPanel2Projects.setLayout(jPanel2ProjectsLayout);
        jPanel2ProjectsLayout.setHorizontalGroup(
            jPanel2ProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2ProjectsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3Projects)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jLabel7ProjectsAdd)
                .addContainerGap())
        );
        jPanel2ProjectsLayout.setVerticalGroup(
            jPanel2ProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2ProjectsLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(jPanel2ProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7ProjectsAdd)
                    .addComponent(jLabel3Projects))
                .addGap(13, 13, 13))
        );

        jPanel3Tasks.setBackground(java.awt.Color.white);
        jPanel3Tasks.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4TasksTitle.setBackground(new java.awt.Color(0, 152, 102));
        jLabel4TasksTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4TasksTitle.setForeground(new java.awt.Color(0, 152, 102));
        jLabel4TasksTitle.setText("Tarefas");
        jLabel4TasksTitle.setMaximumSize(new java.awt.Dimension(70, 25));
        jLabel4TasksTitle.setMinimumSize(new java.awt.Dimension(70, 25));

        jLabel6TasksAdd.setForeground(java.awt.Color.white);
        jLabel6TasksAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        jLabel6TasksAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6TasksAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3TasksLayout = new javax.swing.GroupLayout(jPanel3Tasks);
        jPanel3Tasks.setLayout(jPanel3TasksLayout);
        jPanel3TasksLayout.setHorizontalGroup(
            jPanel3TasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3TasksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4TasksTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6TasksAdd)
                .addContainerGap())
        );
        jPanel3TasksLayout.setVerticalGroup(
            jPanel3TasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3TasksLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel3TasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6TasksAdd)
                    .addComponent(jLabel4TasksTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel4ProjectList.setBackground(java.awt.Color.white);
        jPanel4ProjectList.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jList1Projects.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jList1Projects.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1Projects.setAlignmentX(-1.0F);
        jList1Projects.setAlignmentY(-1.0F);
        jList1Projects.setFixedCellHeight(30);
        jList1Projects.setFixedCellWidth(30);
        jList1Projects.setSelectionBackground(new java.awt.Color(0, 153, 152));
        jList1Projects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1ProjectsMouseClicked(evt);
            }
        });
        jScrollPane1Projects.setViewportView(jList1Projects);

        javax.swing.GroupLayout jPanel4ProjectListLayout = new javax.swing.GroupLayout(jPanel4ProjectList);
        jPanel4ProjectList.setLayout(jPanel4ProjectListLayout);
        jPanel4ProjectListLayout.setHorizontalGroup(
            jPanel4ProjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4ProjectListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1Projects)
                .addContainerGap())
        );
        jPanel4ProjectListLayout.setVerticalGroup(
            jPanel4ProjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4ProjectListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1Projects)
                .addContainerGap())
        );

        jPanel5.setBackground(java.awt.Color.white);
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanelEmptyList.setBackground(java.awt.Color.white);

        jLabel5EmptyListIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5EmptyListIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lists.png"))); // NOI18N

        jLabel8EmptyListTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8EmptyListTitle.setForeground(new java.awt.Color(0, 153, 102));
        jLabel8EmptyListTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8EmptyListTitle.setText("Nenhuma tarefa por aqui!");

        jLabel9EmptyListSubtitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9EmptyListSubtitle.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9EmptyListSubtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9EmptyListSubtitle.setText("Clique no botão \"+\" para adicionar uma nova tarefa");

        javax.swing.GroupLayout jPanelEmptyListLayout = new javax.swing.GroupLayout(jPanelEmptyList);
        jPanelEmptyList.setLayout(jPanelEmptyListLayout);
        jPanelEmptyListLayout.setHorizontalGroup(
            jPanelEmptyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmptyListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEmptyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5EmptyListIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9EmptyListSubtitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8EmptyListTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelEmptyListLayout.setVerticalGroup(
            jPanelEmptyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmptyListLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel5EmptyListIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8EmptyListTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9EmptyListSubtitle)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        jPanel5.add(jPanelEmptyList, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelToolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4ProjectList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2Projects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3Tasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpanelToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2Projects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3Tasks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4ProjectList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7ProjectsAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7ProjectsAddMouseClicked
        // TODO add your handling code here:
        ProjectDialogScreen projectDialogScreen = new ProjectDialogScreen(this, rootPaneCheckingEnabled);
        projectDialogScreen.setVisible(true);

        projectDialogScreen.addWindowListener(new WindowAdapter() {

            public void windowClosed(WindowEvent e) {
                loadProjects();
            }
        });


    }//GEN-LAST:event_jLabel7ProjectsAddMouseClicked

    private void jLabel6TasksAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6TasksAddMouseClicked
        // TODO add your handling code here:
        TaskDialogScreen taskDialogScreen = new TaskDialogScreen(this, rootPaneCheckingEnabled);
        //taskDialogScreen.setProject(null);
        int projectIndex = jList1Projects.getSelectedIndex();
        Project project = (Project) projectsModel.get(projectIndex);
        taskDialogScreen.setProject(project);
        

        taskDialogScreen.setVisible(rootPaneCheckingEnabled);
        
        taskDialogScreen.addWindowListener(new WindowAdapter(){
            public void windowClosed(WindowEvent e){
                int projectIndex = jList1Projects.getSelectedIndex();
                Project project = (Project) projectsModel.get(projectIndex);
                loadTasks(project.getId());
            }
        
        
        });


    }//GEN-LAST:event_jLabel6TasksAddMouseClicked

    private void jTable1TasksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1TasksMouseClicked
        // TODO add your handling code here:
        int rowIndex = jTable1Tasks.rowAtPoint(evt.getPoint());
        int columnIndex = jTable1Tasks.columnAtPoint(evt.getPoint());
        Task task = taskModel.getTasks().get(rowIndex);
        switch (columnIndex) {
            case 3:
                taskController.update(task);
                break;
            case 4:

                break;
            case 5:
                taskController.removeById(task.getId());
                taskModel.getTasks().remove(task);
                int projectIndex = jList1Projects.getSelectedIndex();
                Project project = (Project) projectsModel.get(projectIndex);
                loadTasks(project.getId());
                

                break;
            case 6:
                break;

        }


    }//GEN-LAST:event_jTable1TasksMouseClicked

    private void jList1ProjectsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1ProjectsMouseClicked
        // TODO add your handling code here:
        int projectIndex = jList1Projects.getSelectedIndex();
        Project project = (Project) projectsModel.get(projectIndex);
        loadTasks(project.getId());

    }//GEN-LAST:event_jList1ProjectsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java Swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1ToobarTitle;
    private javax.swing.JLabel jLabel2ToobarSubtitle;
    private javax.swing.JLabel jLabel3Projects;
    private javax.swing.JLabel jLabel4TasksTitle;
    private javax.swing.JLabel jLabel5EmptyListIcon;
    private javax.swing.JLabel jLabel6TasksAdd;
    private javax.swing.JLabel jLabel7ProjectsAdd;
    private javax.swing.JLabel jLabel8EmptyListTitle;
    private javax.swing.JLabel jLabel9EmptyListSubtitle;
    private javax.swing.JList<String> jList1Projects;
    private javax.swing.JPanel jPanel2Projects;
    private javax.swing.JPanel jPanel3Tasks;
    private javax.swing.JPanel jPanel4ProjectList;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelEmptyList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane1Projects;
    private javax.swing.JTable jTable1Tasks;
    private javax.swing.JPanel jpanelToolbar;
    // End of variables declaration//GEN-END:variables

    public void decorateTableTask() {

        //Customizando o header da table de tarefas
        jTable1Tasks.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        jTable1Tasks.getTableHeader().setBackground(new Color(0, 153, 102));
        jTable1Tasks.getTableHeader().setForeground(new Color(255, 255, 255));

        //Criando um sort automatico para as colunas
        jTable1Tasks.setAutoCreateRowSorter(true);

    }

    public void initDataController() {
        projectController = new ProjectController();
        taskController = new TaskController();
    }

    public void initComponentsModel() {
        projectsModel = new DefaultListModel();
        loadProjects();
        taskModel = new TaskTableModel();
        jTable1Tasks.setModel(taskModel);

        
       if (!projectsModel.isEmpty()) {
            jList1Projects.setSelectedIndex(0);
            int projectIndex = jList1Projects.getSelectedIndex();
            Project project = (Project) projectsModel.get(projectIndex);
            loadTasks(project.getId());
        }
            
            

    }

    public void loadTasks(int idProject) {

        List<Task> tasks = taskController.getAll(idProject);
        taskModel.setTasks(tasks);

        showJTableTasks(!tasks.isEmpty());

    }

    private void showJTableTasks(boolean hasTasks) {
        if (hasTasks) {
            if (jPanelEmptyList.isVisible()) {
                jPanelEmptyList.setVisible(false);
                jPanel5.remove(jPanelEmptyList);
            }

            jPanel5.add(jScrollPane1);
            jScrollPane1.setVisible(true);
            jScrollPane1.setSize(jPanel5.getWidth(), jPanel5.getHeight());

        } else {
            if (jScrollPane1.isVisible()) {
                jScrollPane1.setVisible(false);
                jPanel5.remove(jScrollPane1);

            }

            jPanel5.add(jPanelEmptyList);
            jPanelEmptyList.setVisible(true);
            jPanelEmptyList.setSize(jPanel5.getWidth(), jPanel5.getHeight());

        }

    }

    public void loadProjects() {
        List<Project> projects = projectController.getAll();

        projectsModel.clear();

        for (int i = 0; i < projects.size(); i++) {

            Project project = projects.get(i);
            projectsModel.addElement(project);
        }

        jList1Projects.setModel(projectsModel);

    }

}
