/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.ProjectController;
import javax.swing.JOptionPane;
import model.Project;

/**
 *
 * @author Wesley
 */
public class ProjectDialogScreen extends javax.swing.JDialog {
    
    
    ProjectController controller;
    

    /**
     * Creates new form ProjectDialogScreen
     */
    public ProjectDialogScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        controller = new ProjectController();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1Toobar = new javax.swing.JPanel();
        jLabel1ToobarSave = new javax.swing.JLabel();
        jLabel2ToobarTitle = new javax.swing.JLabel();
        jPanel2Project = new javax.swing.JPanel();
        jLabel5NameTitle = new javax.swing.JLabel();
        jTextField2NameField = new javax.swing.JTextField();
        jLabel6DescriptionTItle = new javax.swing.JLabel();
        jScrollPane1DescriptionField = new javax.swing.JScrollPane();
        jTextAreaProjectDescription = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 350));
        setModal(true);
        setPreferredSize(new java.awt.Dimension(400, 350));

        jPanel1Toobar.setBackground(new java.awt.Color(0, 153, 102));
        jPanel1Toobar.setForeground(new java.awt.Color(0, 153, 102));

        jLabel1ToobarSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check.png"))); // NOI18N
        jLabel1ToobarSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1ToobarSaveMouseClicked(evt);
            }
        });

        jLabel2ToobarTitle.setBackground(new java.awt.Color(0, 153, 102));
        jLabel2ToobarTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2ToobarTitle.setForeground(java.awt.Color.white);
        jLabel2ToobarTitle.setText("Projeto");

        javax.swing.GroupLayout jPanel1ToobarLayout = new javax.swing.GroupLayout(jPanel1Toobar);
        jPanel1Toobar.setLayout(jPanel1ToobarLayout);
        jPanel1ToobarLayout.setHorizontalGroup(
            jPanel1ToobarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1ToobarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2ToobarTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1ToobarSave, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1ToobarLayout.setVerticalGroup(
            jPanel1ToobarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1ToobarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1ToobarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1ToobarSave, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1ToobarLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2ToobarTitle))))
        );

        jPanel2Project.setBackground(java.awt.Color.white);

        jLabel5NameTitle.setText("Nome");

        jTextField2NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2NameFieldActionPerformed(evt);
            }
        });

        jLabel6DescriptionTItle.setText("Descrição");

        jTextAreaProjectDescription.setColumns(20);
        jTextAreaProjectDescription.setRows(5);
        jScrollPane1DescriptionField.setViewportView(jTextAreaProjectDescription);

        javax.swing.GroupLayout jPanel2ProjectLayout = new javax.swing.GroupLayout(jPanel2Project);
        jPanel2Project.setLayout(jPanel2ProjectLayout);
        jPanel2ProjectLayout.setHorizontalGroup(
            jPanel2ProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2ProjectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2ProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5NameTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField2NameField)
                    .addComponent(jLabel6DescriptionTItle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1DescriptionField, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)))
        );
        jPanel2ProjectLayout.setVerticalGroup(
            jPanel2ProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2ProjectLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5NameTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6DescriptionTItle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1DescriptionField, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1Toobar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2Project, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1Toobar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2Project, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2NameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2NameFieldActionPerformed

    private void jLabel1ToobarSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1ToobarSaveMouseClicked
        // TODO add your handling code here:
        try {
            Project project = new Project();
            project.setName(jTextField2NameField.getText());
            project.setDescription(jTextAreaProjectDescription.getText());
            controller.save(project);
            JOptionPane.showMessageDialog(rootPane, "Projeto salvo com sucesso");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
        
        
        this.dispose();
    }//GEN-LAST:event_jLabel1ToobarSaveMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java Swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProjectDialogScreen dialog = new ProjectDialogScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1ToobarSave;
    private javax.swing.JLabel jLabel2ToobarTitle;
    private javax.swing.JLabel jLabel5NameTitle;
    private javax.swing.JLabel jLabel6DescriptionTItle;
    private javax.swing.JPanel jPanel1Toobar;
    private javax.swing.JPanel jPanel2Project;
    private javax.swing.JScrollPane jScrollPane1DescriptionField;
    private javax.swing.JTextArea jTextAreaProjectDescription;
    private javax.swing.JTextField jTextField2NameField;
    // End of variables declaration//GEN-END:variables
}
