/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.TaskController;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import model.Project;
import model.Task;

/**
 *
 * @author Wesley
 */
public class TaskDialogScreen extends javax.swing.JDialog {
    
    TaskController controller;
    Project project;

    /**
     * Creates new form TaskDialogScreen
     */
    public TaskDialogScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        controller = new TaskController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1Task = new javax.swing.JPanel();
        jLabel1TaskTitle = new javax.swing.JLabel();
        jLabel2TaskIcon = new javax.swing.JLabel();
        jPanel2TasksFields = new javax.swing.JPanel();
        jLabel3TasksFieldNameTittle = new javax.swing.JLabel();
        jTextField1TasksNameField = new javax.swing.JTextField();
        jLabel4TasksDescriptionTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1TasksDescriptionField = new javax.swing.JTextArea();
        jLabel5TasksDeadlineTitle = new javax.swing.JLabel();
        jLabel6TasksNotesTitle = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2TasksNotesField = new javax.swing.JTextArea();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(350, 600));

        jPanel1Task.setBackground(new java.awt.Color(0, 153, 102));

        jLabel1TaskTitle.setBackground(java.awt.Color.white);
        jLabel1TaskTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1TaskTitle.setForeground(java.awt.Color.white);
        jLabel1TaskTitle.setText("Tarefa");

        jLabel2TaskIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check.png"))); // NOI18N
        jLabel2TaskIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2TaskIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1TaskLayout = new javax.swing.GroupLayout(jPanel1Task);
        jPanel1Task.setLayout(jPanel1TaskLayout);
        jPanel1TaskLayout.setHorizontalGroup(
            jPanel1TaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1TaskLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1TaskTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2TaskIcon)
                .addContainerGap())
        );
        jPanel1TaskLayout.setVerticalGroup(
            jPanel1TaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1TaskLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1TaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1TaskTitle)
                    .addComponent(jLabel2TaskIcon))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel2TasksFields.setBackground(java.awt.Color.white);

        jLabel3TasksFieldNameTittle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3TasksFieldNameTittle.setText("Nome");

        jLabel4TasksDescriptionTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4TasksDescriptionTitle.setText("Descrição");

        jTextArea1TasksDescriptionField.setColumns(20);
        jTextArea1TasksDescriptionField.setRows(5);
        jScrollPane1.setViewportView(jTextArea1TasksDescriptionField);

        jLabel5TasksDeadlineTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5TasksDeadlineTitle.setText("Prazo");

        jLabel6TasksNotesTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6TasksNotesTitle.setText("Notas");

        jTextArea2TasksNotesField.setColumns(20);
        jTextArea2TasksNotesField.setRows(5);
        jScrollPane2.setViewportView(jTextArea2TasksNotesField);

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        javax.swing.GroupLayout jPanel2TasksFieldsLayout = new javax.swing.GroupLayout(jPanel2TasksFields);
        jPanel2TasksFields.setLayout(jPanel2TasksFieldsLayout);
        jPanel2TasksFieldsLayout.setHorizontalGroup(
            jPanel2TasksFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2TasksFieldsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2TasksFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                    .addComponent(jLabel6TasksNotesTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5TasksDeadlineTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4TasksDescriptionTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1TasksNameField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3TasksFieldNameTittle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2TasksFieldsLayout.setVerticalGroup(
            jPanel2TasksFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2TasksFieldsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3TasksFieldNameTittle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1TasksNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4TasksDescriptionTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5TasksDeadlineTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6TasksNotesTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1Task, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2TasksFields, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1Task, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2TasksFields, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2TaskIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2TaskIconMouseClicked
        // TODO add your handling code here:
        try {
            Task task = new Task();
            task.setIdProject(project.getId());
            task.setName(jTextField1TasksNameField.getText());
            task.setDescription(jTextArea1TasksDescriptionField.getText());
            task.setIsCompleted(false);
            task.setNotes(jTextArea2TasksNotesField.getText());

            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            Date deadline = dateFormat.parse(jFormattedTextField1.getText());

            task.setDeadline(deadline);
            JOptionPane.showMessageDialog(rootPane, "Tarefa Salva com sucesso");
            controller.save(task);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
        
        
        this.dispose();

    }//GEN-LAST:event_jLabel2TaskIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TaskDialogScreen dialog = new TaskDialogScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1TaskTitle;
    private javax.swing.JLabel jLabel2TaskIcon;
    private javax.swing.JLabel jLabel3TasksFieldNameTittle;
    private javax.swing.JLabel jLabel4TasksDescriptionTitle;
    private javax.swing.JLabel jLabel5TasksDeadlineTitle;
    private javax.swing.JLabel jLabel6TasksNotesTitle;
    private javax.swing.JPanel jPanel1Task;
    private javax.swing.JPanel jPanel2TasksFields;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1TasksDescriptionField;
    private javax.swing.JTextArea jTextArea2TasksNotesField;
    private javax.swing.JTextField jTextField1TasksNameField;
    // End of variables declaration//GEN-END:variables

    public void setProject(Project project) {
        this.project = project;
    }
    
    
    
}
